"""
BackgroundAudio model for background music tracks.
"""
import enum
from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Enum
from sqlalchemy.orm import relationship
from datetime import datetime

from app.database import Base


class AudioSource(str, enum.Enum):
    """Source of the background audio."""
    UPLOAD = "upload"  # User uploaded
    AI_GENERATED = "ai_generated"  # Generated by AI


class BackgroundAudio(Base):
    """Background music/audio track in a project."""

    __tablename__ = "background_audio"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)

    # File information
    filename = Column(String(255), nullable=False)
    original_name = Column(String(255), nullable=True)

    # Source of the audio
    source = Column(Enum(AudioSource), default=AudioSource.UPLOAD, nullable=False)

    # Timeline position (in seconds)
    start_time = Column(Float, default=0.0)
    duration = Column(Float, nullable=True)  # Duration in seconds

    # Audio settings
    volume = Column(Float, default=0.3)  # 0.0 to 1.0
    fade_in = Column(Float, default=0.0)  # Fade in duration in seconds
    fade_out = Column(Float, default=0.0)  # Fade out duration in seconds

    # AI generation info (if AI generated)
    prompt = Column(String(500), nullable=True)  # Prompt used for generation

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="background_audio")

    def __repr__(self):
        return f"<BackgroundAudio {self.id}: {self.original_name or self.filename}>"
